### PR TITLE
New York Times Replica Microverse Project

### PR DESCRIPTION
**Pull request by m-anwar97**
Merged pull request #1 by mistake
Submitting project with this pull request
Link to the old pull request : https://github.com/Nkuria/New-york-times-clone/pull/1

### CODE REVIEW

**Comment by m-anwar97** [comment]
We tried to reopen pull request #1 but it can't be reopened.

**Comment by kitpao** [comment]
Ok, your feedback will be in the original pull request #1  👍

**Comment by m-anwar97** [comment]
Made the required changes to this pull request
Link to the old pull request that was closed by mistake : https://github.com/Nkuria/New-york-times-clone/pull/1

**Comment by tirthajyoti-ghosh** [comment]
I understand. Check #1 for feedback.

**Comment by m-anwar97** [comment]
Made the required changes on this pull request
Link to old pull request #1

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

## Hello @coldatlas and @Nkuria :wave: 

## You have done an amazing job in this project, congratulations :clap: :clap: :clap: 

## You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
